name: data pipeline

on:
  schedule:
    - cron: '*/2 * * * *'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar script de Python
      run: python main.py

    - name: Commit y push si hay cambios
      run: |
        git config --global user.name 'JuanMaValencia'
        git config --global user.email 'valenciajuan88@gmail.com'
        git add -A
        git commit -m "Actualizar datos" || exit 0   # El comando falla si no hay cambios

    - name: Push cambios
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
