name: Ejecutar script de Python

on: [push]

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run script
      run: python script_ex1.py

    - name: Create a text file
      run: echo "xxlinea nueva new txt file" > output.txt

    - name: Commit text file
      run: |
        git config --global user.name 'JuanMa Valencia'
        git config --global user.email 'valenciajuan88@gmail.com'
        git add output.txt
        git commit -m 'save txt file'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}